### ISSUE TITLE
Map is always full viewport width and height

### ISSUE THREAD

**Issue by anthonynorth** [anthonynorth/rdeck#4]
Map renders full viewport width and height; should be constrained by the map container. Probably a one-liner fix:

```css
.rdeck {
  position: relative;
}
```
